version: "3.8"

networks:
  docknode-pol:
    driver: bridge

volumes:
  caddy_data: {}
  caddy_config: {}

services:
  heimdall:
    image: "0xpolygon/heimdall:latest"
    restart: unless-stopped
    ports:
      - "26656:26656"
    expose:
      - 26657
    volumes:
      - "./heimdall/config:/heimdall-home/config"
      - "./heimdall/data:/heimdall-home/data"
    entrypoint: /usr/bin/heimdalld
    command: >
      start
      --home=/heimdall-home
      --chain=mainnet
    networks:
      - docknode-pol

  heimdallrest:
    image: "0xpolygon/heimdall:latest"
    restart: unless-stopped
    expose:
      - 1317
    volumes:
      - "./heimdall/config:/heimdall-home/config"
      - "./heimdall/data:/heimdall-home/data"
    entrypoint: /usr/bin/heimdalld
    command: >
      rest-server
      --home=/heimdall-home
      --chain=mainnet
      --node "tcp://heimdall:26657"
    networks:
      - docknode-pol
    depends_on:
      - heimdall

  nodeexporter:
    image: prom/node-exporter:v1.5.0
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    networks:
      - docknode-pol

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "9100:9100"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - METRICS_USERS=${METRICS_USERS:?err}
      - RPC_USERS=${RPC_USERS:?err}
      - HOST=${HOST:?err}
    networks:
      - docknode-pol
